modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/Matyrobbrt/MatyLib/issues/" #optional
[[mods]] #mandatory
modId="matylib" #mandatory
version="3.${version}" #mandatory
displayName="MatyLib" #mandatory
#updateJSONURL="https://raw.githubusercontent.com/Matyrobbrt/MatyLib/1.18.2/versions_forge_system.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/matylib" #optional
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="Matyrobbrt" #optional
description='''
A library mod which will be used by most of my mods.
'''
[[dependencies.matylib]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.matylib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
